version: '3'

services:
  nginx:
    image: nginx:latest
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=basket.javiergonzalez.site
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=basket.javiergonzalez.site
      - LETSENCRYPT_EMAIL=admin@gmail.com
    volumes:
      - /home/ubuntu/basket:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    name: nginx-proxy
    external: true